// Code Generated By 'npm run config', Please DO NOT Edit!!!!! 
        
const config = {
    appId: "cli_***************", //网页应用appId
    appSecret: "************************", //网页应用secret
    getUserAccessTokenPath:  "/api/get_user_access_token", //免登-获取user_access_token的api path
    getSignParametersPath:  "/api/get_sign_parameters", //鉴权-获取鉴权参数的api path
    noncestr: "************************",   //随机字符串，用于鉴权签名用
    apiPort: "8989",   //后端指定端口
}
    
module.exports = { config : config };